### ISSUE TITLE
pagerduty provider v1.6.1 seems broken

### ISSUE THREAD

**Issue by chenrui333** [terraform-providers/terraform-provider-pagerduty#204]
Here is the error log I have got (which works for v1.5.1)

```
panic: runtime error: invalid memory address or nil pointer dereference
2020-04-14T20:05:56.008Z [DEBUG] plugin.terraform-provider-pagerduty_v1.6.1_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd326cb]
2020-04-14T20:05:56.008Z [DEBUG] plugin.terraform-provider-pagerduty_v1.6.1_x4: 
2020-04-14T20:05:56.008Z [DEBUG] plugin.terraform-provider-pagerduty_v1.6.1_x4: goroutine 59 [running]:
2020-04-14T20:05:56.008Z [DEBUG] plugin.terraform-provider-pagerduty_v1.6.1_x4: github.com/terraform-providers/terraform-provider-pagerduty/pagerduty.resourcePagerDutyServiceIntegrationRead.func1(0xc0002ee500)
2020-04-14T20:05:56.008Z [DEBUG] plugin.terraform-provider-pagerduty_v1.6.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-pagerduty/pagerduty/resource_pagerduty_service_integration.go:147 +0xdb
2020-04-14T20:05:56.008Z [DEBUG] plugin.terraform-provider-pagerduty_v1.6.1_x4: github.com/hashicorp/terraform-plugin-sdk/helper/resource.Retry.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
2020-04-14T20:05:56.008Z [DEBUG] plugin.terraform-provider-pagerduty_v1.6.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-pagerduty/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/resource/wait.go:22 +0x4e
2020-04-14T20:05:56.008Z [DEBUG] plugin.terraform-provider-pagerduty_v1.6.1_x4: github.com/hashicorp/terraform-plugin-sdk/helper/resource.(*StateChangeConf).WaitForState.func1(0xc0004293e0, 0xc0002ccb60, 0xc0000c6300, 0xc000041c20, 0xc000099600, 0xc0000995f8)
2020-04-14T20:05:56.008Z [DEBUG] plugin.terraform-provider-pagerduty_v1.6.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-pagerduty/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/resource/state.go:103 +0x29e
2020-04-14T20:05:56.008Z [DEBUG] plugin.terraform-provider-pagerduty_v1.6.1_x4: created by github.com/hashicorp/terraform-plugin-sdk/helper/resource.(*StateChangeConf).WaitForState
2020-04-14T20:05:56.008Z [DEBUG] plugin.terraform-provider-pagerduty_v1.6.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-pagerduty/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/resource/state.go:80 +0x1b9
2020-04-14T20:05:56.009Z [DEBUG] plugin: plugin process exited: path=/home/travis/build/meetup/meetup-pagerduty-config/.terraform/plugins/linux_amd64/terraform-provider-pagerduty_v1.6.1_x4 pid=3348 error="exit status 2"
2020/04/14 20:05:56 [ERROR] <root>: eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2020/04/14 20:05:56 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
```

**Comment by chenrui333** [comment]
The interesting thing is it used to work in the previous CI builds.

**Comment by tsein-stripe** [comment]
We also ran into this issue.

Repro steps:
1. Create a new `pagerduty_service_integration` resource with `service = "<pd_service_id_1>"`
2. Plan / apply
3. Change the resource, `service = "<pd_service_id_2>"`
4. Plan (success)
5. Apply (panic)
6. Plan (panic)

From here on the Terraform state is corrupt because it changes the `primary.attributes.html_url` value in the state for this resource to reference the new service ID, e.g. `https://pagerduty.com/services/<pd_service_id_2>/integrations/<pd_integration_id>` but it doesn't seem to actually make that change in PagerDuty itself, e.g. if you navigate to the integration page of `<pd_service_id_1>` it will still show the previously created integration, and if you navigate to `<pd_service_id_2>` it will not show the integration that should have been moved over to it.

To work around this for now we manually moved the integration over from `<pd_service_id_1>` to `<pd_service_id_2>` within the PagerDuty web UI under the service integration tab by using the "Move to Another Service" action.

This fixed the panic because the state now matched the actual state of PagerDuty.

A recent change went into this code path setting up some retry logic for service integration change/creation. But I don't know enough about this code base to determine if this is causing the problem or just making it visible:
https://github.com/terraform-providers/terraform-provider-pagerduty/commit/8352f75539aeb604af04ff7c88eff17e6dd5b0f6#diff-ad8d4e5ec17fb69da5140892e36a899dR138-R145

**Comment by chenrui333** [comment]
cc @stmcallister

**Comment by stmcallister** [comment]
Thanks for posting this! I'm working with @heimweh to figure out a solution. He's proposed an idea that I like and we'll hopefully get it merged in soon.

**Comment by chenrui333** [comment]
Perfect, thanks for the update!!
